# The URL the site will be built for
base_url = "https://appimage-sig.github.io/appimages"

title = "Appimage Catalog for Linux users"
description = "AppImage catalog for Linux users"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = [ "rss.xml",]
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "tags", feed = true},
    { name = "categories", paginate_by = 5 }, # 5 items per page for a term
    { name = "authors" },                     # Basic definition: no feed or pagination
    { name = "frameworks" },
    { name = "architectures" },
    { name = "license" },
]

[markdown.highlighting]
style = "class"
light_theme = "monokai-light"
dark_theme = "monokai"
extra_themes = [
  "giallo/themes/monokai-light.json",
  "giallo/themes/monokai.json",
]

[extra]
logo_image = "images/logo.svg"
social_media_share_image = "/images/01.jpg"
disqus_identifier = ""
twitter_handle = ""

author_image = '/images/avatar.jpg'

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/apps", title = "Apps" },
    { url = "", title = "Categories", submenu = [
        { url = "$BASE_URL/categories/audiovideo", title = "Audio & Video" },
        { url = "$BASE_URL/categories/development", title = "Development" },
        { url = "$BASE_URL/categories/finance", title = "Finance" },
        { url = "$BASE_URL/categories/games", title = "Games" },
        { url = "$BASE_URL/categories/graphics", title = "Graphics" },
        { url = "$BASE_URL/categories/network", title = "Network" },
        { url = "$BASE_URL/categories/productivity", title = "Productivity" },
        { url = "$BASE_URL/categories/science", title = "Science" },
        { url = "$BASE_URL/categories/system", title = "System" },
        { url = "$BASE_URL/categories/utilities", title = "Utilities" },
    ] }
]
social_icons = [
    { url = "https://github.com/appimage-sig", icon = "GitHub" },
    { url = "$BASE_URL/atom.xml", icon = "RSS" },
]
date_format = "%d %b %Y"
language_direction = "auto"
keywords = ["AppImage", "Linux", "Software Center", "Software Catalog"]

[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Home" },
        { url = "$BASE_URL/categories/audiovideo", title = "Audio & Video" },
        { url = "$BASE_URL/categories/development", title = "Development" },
        { url = "$BASE_URL/categories/finance", title = "Finance" },
        { url = "$BASE_URL/categories/games", title = "Games" },
        { url = "$BASE_URL/categories/graphics", title = "Graphics" },
        { url = "$BASE_URL/categories/network", title = "Network" },
        { url = "$BASE_URL/categories/productivity", title = "Productivity" },
        { url = "$BASE_URL/categories/science", title = "Science" },
        { url = "$BASE_URL/categories/system", title = "System" },
        { url = "$BASE_URL/categories/utilities", title = "Utilities" },
]
copyright = "DrSheppard01 2026"

[[extra.content_blocks]]
block = "blog-section"
title = "Recently updated apps"
description_html = """
    <p>AppImage catalog for Linux users</p>"""
link_url = "apps"
show_posts = true
