
"""
AppImage metadata checker for appimage-sig/appimages repository.
Expects metainfo.xml files in the same directory as AppImage files.
Some code was generated by @Claude
Origianlly developed for https://framagit.org/linuxphoneapps/linuxphoneapps.frama.io/-/blob/main/checkers/check_via_appstream.py.
"""



import argparse
import asyncio
import datetime
import logging
import re
import sys
from pathlib import Path
from typing import Any, Literal, TypeAlias
from collections.abc import Callable

import aiofiles
import appstream_python
import httpx

App: TypeAlias = appstream_python.AppstreamComponent
Relation: TypeAlias = Literal["requires", "recommends", "supports"]
Metadata: TypeAlias = dict[str, Any]


class Property:
    def __init__(self, key: str, handler: Callable):
        self.key = key
        self.handler = handler


async def load_appstream_from_file(metainfo_path: Path) -> App | None:
    """Load AppStream metainfo from local XML file."""
    if not metainfo_path.exists():
        logging.warning(f"Metainfo file not found: {metainfo_path}")
        return None
    
    app = App()
    try:
        content = await aiofiles.open(metainfo_path, mode="rb")
        async with content as f:
            data = await f.read()
        app.load_bytes(data, encoding="utf-8")
    except Exception as e:
        logging.error(f"Error loading {metainfo_path}:", exc_info=e)
        return None
    return app


def get_appimage_filename(appimage_path: Path) -> str:
    """Extract AppImage filename without extension."""
    return appimage_path.stem


def get_appstream_name(app: App, *args) -> str:
    return app.name.get_default_text()


def get_appstream_summary(app: App, *args) -> str:
    return app.summary.get_default_text()


def get_appstream_url(app: App, url_type: str, *args) -> str:
    return app.urls.get(url_type, "") or ""


def get_appstream_categories(app: App, *args) -> list[str]:
    return app.categories


def get_appstream_version(app: App, *args) -> str:
    if hasattr(app, 'release') and app.release:
        releases = list(app.release.items()) if isinstance(app.release, dict) else [app.release]
        if releases:
            return str(releases[0].version) if hasattr(releases[0], 'version') else ""
    return ""


def get_appstream_license(app: App, *args) -> str:
    return app.project_license if hasattr(app, 'project_license') else ""


async def check_appimage(appimage_path: Path, update: bool = False) -> bool:
    """
    Check AppImage against its metainfo.xml file.
    Looks for metainfo.xml in the same directory as the AppImage.
    """
    # Find metainfo.xml in the same directory
    metainfo_path = appimage_path.parent / f"{appimage_path.stem}.metainfo.xml"
    
    if not metainfo_path.exists():
        logging.warning(f"No metainfo found for {appimage_path.name}, expected {metainfo_path.name}")
        return False
    
    app = await load_appstream_from_file(metainfo_path)
    if not app:
        return False
    
    appimage_name = get_appimage_filename(appimage_path)
    found_issues = False
    
    properties = [
        Property("name", get_appstream_name),
        Property("summary", get_appstream_summary),
        Property("version", get_appstream_version),
        Property("homepage", lambda app, *args: get_appstream_url(app, "homepage", *args)),
        Property("license", get_appstream_license),
        Property("categories", get_appstream_categories),
    ]
    
    metadata = {}
    for prop in properties:
        try:
            value = prop.handler(app)
            if value:
                metadata[prop.key] = value
                logging.info(f"{appimage_name}: {prop.key} = {value}")
        except Exception as e:
            logging.warning(f"{appimage_name}: Error extracting {prop.key}:", exc_info=e)
    
    # Create or update a metadata file next to AppImage
    metadata_file = appimage_path.parent / f"{appimage_path.stem}.metadata.txt"
    if update or not metadata_file.exists():
        try:
            async with aiofiles.open(metadata_file, mode="w", encoding="utf-8") as f:
                for key, value in metadata.items():
                    await f.write(f"{key}: {value}\n")
            logging.info(f"Metadata written to {metadata_file}")
            found_issues = True
        except Exception as e:
            logging.error(f"Error writing metadata: {e}")
    
    return found_issues


async def check_directory(path: Path, update: bool = False) -> bool:
    """Check all AppImages in a directory."""
    appimages = list(path.glob("*.AppImage"))
    
    if not appimages:
        logging.warning(f"No AppImage files found in {path}")
        return False
    
    tasks = []
    for appimage in appimages:
        tasks.append(check_appimage(appimage, update))
    
    results = await asyncio.gather(*tasks)
    return any(results)


async def validate_metainfo(metainfo_path: Path) -> bool:
    """Validate a metainfo.xml file."""
    app = await load_appstream_from_file(metainfo_path)
    if not app:
        return False
    
    checks = [
        ("ID", app.id),
        ("Name", app.name.get_default_text() if app.name else ""),
        ("Summary", app.summary.get_default_text() if app.summary else ""),
    ]
    
    all_ok = True
    for check_name, value in checks:
        if not value:
            logging.error(f"{metainfo_path.name}: Missing {check_name}")
            all_ok = False
        else:
            logging.info(f"{metainfo_path.name}: ✓ {check_name}: {value}")
    
    return all_ok


async def main() -> None:
    parser = argparse.ArgumentParser(
        description="Check AppImage metadata files for appimage-sig/appimages"
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    
    subparsers = parser.add_subparsers(dest="mode", required=True)
    
    # Check mode
    check_parser = subparsers.add_parser("check", help="Validate AppImages against metainfo files")
    check_parser.add_argument("path", type=Path, help="Path to folder containing AppImages")
    
    # Validate mode
    validate_parser = subparsers.add_parser("validate", help="Validate metainfo.xml files")
    validate_parser.add_argument("path", type=Path, help="Path to metainfo.xml file or folder")
    
    # Extract mode
    extract_parser = subparsers.add_parser("extract", help="Extract metadata from metainfo files")
    extract_parser.add_argument("path", type=Path, help="Path to metainfo.xml file")
    
    args = parser.parse_args()
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    if args.mode == "check":
        if not args.path.is_dir():
            logging.error(f"Path must be a directory: {args.path}")
            sys.exit(1)
        found = await check_directory(args.path, update=False)
        if not found:
            logging.info("All AppImages validated successfully")
        sys.exit(0 if not found else 1)
    
    elif args.mode == "validate":
        if args.path.is_file():
            found = await validate_metainfo(args.path)
        else:
            metainfo_files = list(args.path.glob("*.metainfo.xml"))
            if not metainfo_files:
                logging.error(f"No metainfo files found in {args.path}")
                sys.exit(1)
            tasks = [validate_metainfo(f) for f in metainfo_files]
            results = await asyncio.gather(*tasks)
            found = all(results)
        sys.exit(0 if found else 1)
    
    elif args.mode == "extract":
        app = await load_appstream_from_file(args.path)
        if app:
            print(f"ID: {app.id}")
            print(f"Name: {app.name.get_default_text()}")
            print(f"Summary: {app.summary.get_default_text()}")
            print(f"License: {app.project_license}")
            print(f"Categories: {', '.join(app.categories)}")


if __name__ == "__main__":
    asyncio.run(main())