#!/usr/bin/env sh

set -e

wget -q https://raw.githubusercontent.com/86Box/86Box/refs/heads/master/src/unix/assets/net.86box.86Box.metainfo.xml -O ./content/apps/86box/net.86box.86Box.metainfo.xml &
wget -q https://raw.githubusercontent.com/actualbudget/actual/refs/heads/master/packages/desktop-electron/extra-resources/linux/com.actualbudget.actual.metainfo.xml -O ./content/apps/actual/com.actualbudget.actual.metainfo.xml &
wget -q https://raw.githubusercontent.com/toeverything/AFFiNE/refs/heads/canary/packages/frontend/apps/electron/resources/affine.metainfo.xml -O ./content/apps/affine/org.toeverything.AFFiNE.metainfo.xml &
wget -q https://raw.githubusercontent.com/Umio-Yasuno/amdgpu_top/refs/heads/main/assets/io.github.umio_yasuno.amdgpu_top.metainfo.xml -O ./content/apps/amdgpu_top/io.github.umio_yasuno.amdgpu_top.metainfo.xml &
wget -q https://raw.githubusercontent.com/antares-sql/antares/refs/heads/master/assets/flatpak/it.fabiodistasio.AntaresSQL.metainfo.xml -O ./content/apps/antares/it.fabiodistasio.AntaresSQL.metainfo.xml &
wget -q https://raw.githubusercontent.com/AntiMicroX/antimicrox/refs/heads/master/other/appdata/io.github.antimicrox.antimicrox.appdata.xml.in -O ./content/apps/antimicrox/io.github.antimicrox.antimicrox.metainfo.xml &
wget -q https://raw.githubusercontent.com/AppFlowy-IO/AppFlowy/refs/heads/main/frontend/scripts/flatpack-buildfiles/io.appflowy.AppFlowy.metainfo.xml -O ./content/apps/appflowy/io.appflowy.AppFlowy.metainfo.xml &
wget -q https://raw.githubusercontent.com/audacity/audacity/refs/heads/master/buildscripts/packaging/Linux%2BBSD/org.audacityteam.Audacity.appdata.xml.in -O ./content/apps/audacity/org.audacityteam.Audacity.metainfo.xml &
wget -q https://raw.githubusercontent.com/Beaver-Notes/Beaver-Notes/refs/heads/development/flatpak/com.beavernotes.beavernotes.metainfo.xml -O ./content/apps/beavernotes/com.beavernotes.beavernotes.metainfo.xml &
wget -q https://raw.githubusercontent.com/LinwoodDev/Butterfly/refs/heads/develop/app/linux/debian/usr/share/metainfo/dev.linwood.butterfly.appdata.xml -O ./content/apps/butterfly/dev.linwood.butterfly.metainfo.xml &
wget -q https://raw.githubusercontent.com/danirod/cartero/refs/heads/trunk/data/es.danirod.Cartero.metainfo.xml.in.in -O ./content/apps/cartero/es.danirod.Cartero.metainfo.xml &
wget -q https://raw.githubusercontent.com/streetpea/chiaki-ng/refs/heads/main/gui/io.github.streetpea.Chiaki4deck.appdata.xml -O ./content/apps/chiaki-ng/io.github.streetpea.Chiaki4deck.metainfo.xml &
wget -q https://raw.githubusercontent.com/Faster3ck/Converseen/refs/heads/main/converseen.appdata.xml -O ./content/apps/converseen/net.fasterland.Converseen.metainfo.xml &
wget -q https://raw.githubusercontent.com/cpeditor/cpeditor/refs/heads/master/cmake/cpeditor.appdata.xml.in -O ./content/apps/cpeditor/io.github.cpeditor.cpeditor.metainfo.xml &
wget -q https://raw.githubusercontent.com/TheTumultuousUnicornOfDarkness/CPU-X/refs/heads/master/data/io.github.thetumultuousunicornofdarkness.cpu-x.appdata.xml -O ./content/apps//cpu-x/io.github.thetumultuousunicornofdarkness.cpu-x.metainfo.xml &
wget -q https://raw.githubusercontent.com/cryptomator/cryptomator/refs/heads/develop/dist/linux/common/org.cryptomator.Cryptomator.metainfo.xml -O ./content/apps/cryptomator/org.cryptomator.Cryptomator.metainfo.xml &
wget -q https://raw.githubusercontent.com/Ultimaker/Cura/refs/heads/main/packaging/AppImage/cura.appdata.xml -O ./content/apps/cura/com.ultimaker.Cura.metainfo.xml &
wget -q https://raw.githubusercontent.com/rizinorg/cutter/refs/heads/dev/src/re.rizin.cutter.appdata.xml -O ./content/apps/cutter/re.rizin.cutter.metainfo.xml &
wget -q https://raw.githubusercontent.com/darktable-org/darktable/refs/heads/master/data/org.darktable.darktable.appdata.xml.in -O ./content/apps/darktable/org.darktable.darktable.metainfo.xml &
wget -q https://raw.githubusercontent.com/dbgate/dbgate/refs/heads/master/app/org.dbgate.DbGate.metainfo.xml/org.dbgate.DbGate.metainfo.xml -O ./content/apps/dbgate/org.dbgate.DbGate.metainfo.xml &
wget -q https://raw.githubusercontent.com/deltachat/deltachat-desktop/refs/heads/main/packages/target-tauri/metainfo.xml -O ./content/apps/deltachat/org.deltachat.DeltaChat.metainfo.xml &
wget -q https://raw.githubusercontent.com/diasurgical/DevilutionX/refs/heads/master/Packaging/nix/devilutionx.metainfo.xml -O ./content/apps/devilutionx/org.diasurgical.DevilutionX.metainfo.xml &
wget -q https://invent.kde.org/graphics/digikam/-/raw/master/core/app/main/org.kde.digikam.appdata.xml -O ./content/apps/digikam/org.kde.digikam.metainfo.xml &
wget -q https://raw.githubusercontent.com/stenzek/duckstation/refs/heads/master/scripts/appimage/org.duckstation.DuckStation.metainfo.xml.in -O ./content/apps/duckstation/org.duckstation.DuckStation.metainfo.xml &
wget -q https://raw.githubusercontent.com/ente-io/ente/refs/heads/main/mobile/apps/auth/linux/packaging/enteauth.appdata.xml -O ./content/apps/ente-auth/io.ente.auth.metainfo.xml &
wget -q https://raw.githubusercontent.com/ente-io/ente/refs/heads/main/desktop/build/io.ente.photos.appdata.xml -O ./content/apps/ente-photos/io.ente.photos.metainfo.xml &
wget -q https://raw.githubusercontent.com/feather-wallet/feather/refs/heads/master/src/assets/org.featherwallet.feather.metainfo.xml -O ./content/apps/feather/org.featherwallet.feather.metainfo.xml &
wget -q https://raw.githubusercontent.com/jeffvli/feishin/refs/heads/development/org.jeffvli.feishin.metainfo.xml -O ./content/apps/feishin/org.jeffvli.feishin.metainfo.xml &
wget -q https://raw.githubusercontent.com/garuda-linux/firedragon/refs/heads/main/assets/org.garudalinux.firedragon.metainfo.xml -O ./content/apps/firedragon/org.garudalinux.firedragon.metainfo.xml &
wget -q https://raw.githubusercontent.com/flacon/flacon/refs/heads/master/misc/com.github.Flacon.metainfo.xml.in -O ./content/apps/flacon/io.github.flacon.Flacon.metainfo.xml &
wget -q https://raw.githubusercontent.com/flareteam/flare-game/refs/heads/master/distribution/org.flarerpg.Flare.appdata.xml -O ./content/apps/flare/org.flarerpg.Flare.metainfo.xml &
wget -q https://raw.githubusercontent.com/LinwoodDev/Flow/refs/heads/develop/app/linux/debian/usr/share/metainfo/dev.linwood.flow.appdata.xml -O ./content/apps/flow/dev.linwood.Flow.metainfo.xml &
wget -q https://raw.githubusercontent.com/flyinghead/flycast/refs/heads/master/shell/linux/org.flycast.Flycast.metainfo.xml -O ./content/apps/flycast/org.flycast.Flycast.metainfo.xml &
wget -q https://raw.githubusercontent.com/fontforge/fontforge/refs/heads/master/desktop/org.fontforge.FontForge.appdata.xml.in -O ./content/apps/fontforge/org.fontforge.FontForge.metainfo.xml &
wget -q https://raw.githubusercontent.com/enzo1982/freac/refs/heads/master/metadata/org.freac.freac.appdata.xml -O ./content/apps/freac/org.freac.freac.metainfo.xml &
wget -q https://raw.githubusercontent.com/FreeCAD/FreeCAD/refs/heads/main/src/XDGData/org.freecad.FreeCAD.metainfo.xml.in -O ./content/apps/freecad/org.freecad.FreeCAD.metainfo.xml &
wget -q https://raw.githubusercontent.com/casimir/frigoligo/refs/heads/main/flathub/net.casimirlab.frigoligo.metainfo.xml -O ./content/apps/frigoligo/net.casimirlab.frigoligo.metainfo.xml &
wget -q https://gitlab.gnome.org/GNOME/gimp/-/raw/master/desktop/org.gimp.GIMP.appdata.xml.in.in -O ./content/apps/gimp/org.gimp.GIMP.metainfo.xml &
wget -q https://invent.kde.org/graphics/glaxnimate/-/raw/master/deploy/org.kde.glaxnimate.metainfo.xml?ref_type=heads -O ./content/apps/glaxnimate/org.kde.glaxnimate.metainfo.xml &
wget -q https://raw.githubusercontent.com/jorio/gitfourchette/refs/heads/master/pkg/flatpak/org.gitfourchette.gitfourchette.metainfo.xml  -O ./content/apps/gitfourchette/org.gitfourchette.gitfourchette.metainfo.xml &
wget -q https://gitlab.com/inkscape/inkscape/-/raw/master/org.inkscape.Inkscape.appdata.xml.in?ref_type=heads -O ./content/apps/inkscape/org.inkscape.Inkscape.metainfo.xml &
wget -q https://invent.kde.org/multimedia/kdenlive/-/raw/master/data/org.kde.kdenlive.appdata.xml -O ./content/apps/kdenlive/org.kde.kdenlive.metainfo.xml &
wget -q https://raw.githubusercontent.com/keepassxreboot/keepassxc/refs/heads/develop/share/linux/org.keepassxc.KeePassXC.appdata.xml -O ./content/apps/keepassxc/org.keepassxc.KeePassXC.metainfo.xml &
wget -q https://raw.githubusercontent.com/koreader/koreader/refs/heads/master/platform/linux/koreader.metainfo.xml -O ./content/apps/koreader/koreader.metainfo.xml &
wget -q https://invent.kde.org/graphics/krita/-/raw/master/krita/org.kde.krita.appdata.xml -O ./content/apps/krita/org.kde.krita.metainfo.xml &
wget -q https://raw.githubusercontent.com/ksnip/ksnip/refs/heads/master/desktop/org.ksnip.ksnip.appdata.xml -O ./content/apps/ksnip/org.ksnip.ksnip.metainfo.xml &
wget -q https://raw.githubusercontent.com/azagaya/laigter/refs/heads/master/dist/laigter.appdata.xml -O ./content/apps/laigter/io.github.azagaya.Laigter.metainfo.xml &
wget -q https://raw.githubusercontent.com/Legcord/Legcord/refs/heads/dev/meta/app.legcord.Legcord.metainfo.xml -O ./content/apps/legcord/app.legcord.Legcord.metainfo.xml &
wget -q https://raw.githubusercontent.com/leozide/leocad/refs/heads/master/tools/setup/leocad.appdata.xml -O ./content/apps/leocad/org.leocad.LeoCAD.metainfo.xml &
wget -q https://raw.githubusercontent.com/LibreCAD/LibreCAD/refs/heads/master/desktop/org.librecad.librecad.appdata.xml -O ./content/apps/librecad/org.librecad.librecad.metainfo.xml &
wget -q https://gitlab.com/librewolf-community/browser/appimage/-/raw/master/io.gitlab.librewolf-community.appdata.xml.in?ref_type=heads -O ./content/apps/librewolf/io.gitlab.librewolf-community.metainfo.xml
wget -q https://raw.githubusercontent.com/lite-xl/lite-xl/refs/heads/master/resources/linux/com.lite_xl.LiteXL.metainfo.xml.in -O ./content/apps/lite-xl/com.lite_xl.LiteXL.metainfo.xml &
wget -q https://raw.githubusercontent.com/mifi/lossless-cut/refs/heads/master/no.mifi.losslesscut.appdata.xml -O ./content/apps/losslesscut/no.mifi.losslesscut.metainfo.xml &
wget -q https://raw.githubusercontent.com/myst6re/makoureactor/refs/heads/master/deploy/linux/io.github.myst6re.makoureactor.metainfo.xml -O ./content/apps/makoureactor/io.github.myst6re.makoureactor.metainfo.xml &
wget -q https://raw.githubusercontent.com/musescore/MuseScore/refs/heads/master/buildscripts/packaging/Linux%2BBSD/org.musescore.MuseScore.appdata.xml.in -O ./content/apps/musescore/org.musescore.MuseScore.metainfo.xml &
wget -q https://raw.githubusercontent.com/Sandakan/Nora/refs/heads/master/flatpak/app.netlify.noramusic.Nora.metainfo.xml -O ./content/apps/nora/app.netlify.noramusic.Nora.metainfo.xml &
wget -q https://raw.githubusercontent.com/dail8859/NotepadNext/refs/heads/master/deploy/linux/com.github.dail8859.NotepadNext.metainfo.xml  -O ./content/apps/notepadnext/com.github.dail8859.NotepadNext.metainfo.xml &
wget -q https://raw.githubusercontent.com/nuttyartist/notes/refs/heads/master/packaging/linux/common/notes.appdata.xml.in -O ./content/apps/notes/io.github.nuttyartist.notes.metainfo.xml &
wget -q https://raw.githubusercontent.com/nukeop/nuclear/refs/heads/master/packages/player/src-tauri/resources/com.nuclearplayer.Nuclear.metainfo.xml -O ./content/apps/nuclear/com.nuclearplayer.Nuclear.metainfo.xml &
wget -q https://raw.githubusercontent.com/neovim/neovim/refs/heads/master/runtime/nvim.appdata.xml -O ./content/apps/neovim/io.neovim.nvim.metainfo.xml &
wget -q https://raw.githubusercontent.com/Syllo/nvtop/refs/heads/master/desktop/nvtop.metainfo.xml -O ./content/apps/nvtop/io.github.syllo.nvtop.metainfo.xml &
wget -q https://gitlab.com/CalcProgrammer1/OpenRGB/-/raw/master/qt/org.openrgb.OpenRGB.metainfo.xml -O ./content/apps/openrgb/org.openrgb.OpenRGB.metainfo.xml &
wget -q https://raw.githubusercontent.com/openscad/openscad/refs/heads/master/openscad.appdata.xml.in -O ./content/apps/openscad/org.openscad.OpenSCAD.metainfo.xml &
wget -q https://raw.githubusercontent.com/OpenShot/openshot-qt/refs/heads/develop/xdg/org.openshot.OpenShot.appdata.xml -O ./content/apps/openshot/org.openshot.OpenShot.metainfo.xml &
wget -q https://raw.githubusercontent.com/GlitterWare/Passy/refs/heads/main/linux_assets/com.glitterware.passy.appdata.xml  -O ./content/apps/passy/com.glitterware.passy.metainfo.xml &
wget -q https://raw.githubusercontent.com/PCSX2/pcsx2/refs/heads/master/.github/workflows/scripts/linux/pcsx2-qt.metainfo.xml.in -O ./content/apps/pcsx2/pcsx2-qt.metainfo.xml &
wget -q https://raw.githubusercontent.com/pencil2d/pencil/refs/heads/master/app/data/org.pencil2d.Pencil2D.metainfo.xml -O ./content/apps/pencil2d/org.pencil2d.Pencil2D.metainfo.xml &
wget -q https://gitlab.com/lspies/photoqt/-/raw/master/org.photoqt.PhotoQt.metainfo.xml -O ./content/apps/photoqt/org.photoqt.PhotoQt.metainfo.xml &
wget -q https://raw.githubusercontent.com/jpd002/Play-/refs/heads/master/installer_unix/org.purei.Play.metainfo.xml -O ./content/apps/play/org.purei.Play.metainfo.xml &
wget -q https://raw.githubusercontent.com/PrismLauncher/PrismLauncher/refs/heads/develop/program_info/org.prismlauncher.PrismLauncher.metainfo.xml -O ./content/apps/prismlauncher/org.prismlauncher.PrismLauncher.metainfo.xml &
wget -q https://raw.githubusercontent.com/DavidoTek/ProtonUp-Qt/refs/heads/main/share/metainfo/net.davidotek.pupgui2.appdata.xml -O ./content/apps/protonup-qt/net.davidotek.pupgui2.metainfo.xml &
wget -q https://raw.githubusercontent.com/pulsar-edit/pulsar/refs/heads/master/resources/linux/dev.pulsar_edit.Pulsar.metainfo.xml -O ./content/apps/pulsar/dev.pulsar_edit.Pulsar.metainfo.xml &
wget -q https://raw.githubusercontent.com/c0re100/qBittorrent-Enhanced-Edition/refs/heads/v5_1_x/dist/unix/org.qbittorrent.qBittorrent.metainfo.xml -O ./content/apps/qbittorrent/org.qbittorrent.qBittorrent.metainfo.xml &
wget -q https://raw.githubusercontent.com/opengisch/QField/refs/heads/master/platform/linux/qfield.metainfo.xml -O ./content/apps/qfield/org.qfield.QField.metainfo.xml &
wget -q https://raw.githubusercontent.com/zaps166/QMPlay2/refs/heads/master/src/gui/Unix/QMPlay2.appdata.xml.in -O ./content/apps/qmplay2/io.github.zaps166.QMPlay2.metainfo.xml &
wget -q https://raw.githubusercontent.com/pbek/QOwnNotes/refs/heads/main/obs/qownnotes.appdata.xml -O ./content/apps/qownnotes/io.github.pbek.QOwnNotes.metainfo.xml &
wget -q https://raw.githubusercontent.com/CyberTimon/RapidRAW/refs/heads/main/data/io.github.CyberTimon.RapidRAW.metainfo.xml -O ./content/apps/rapidraw/io.github.CyberTimon.RapidRAW.metainfo.xml &
wget -q https://raw.githubusercontent.com/RawTherapee/RawTherapee/refs/heads/dev/com.rawtherapee.RawTherapee.appdata.xml -O ./content/apps/rawtherapee/com.rawtherapee.RawTherapee.metainfo.xml &
wget -q https://raw.githubusercontent.com/ColinKinloch/RetroArch/refs/heads/master/com.libretro.RetroArch.metainfo.xml -O ./content/apps/retroarch/com.libretro.RetroArch.metainfo.xml &
wget -q https://raw.githubusercontent.com/RPCS3/rpcs3/refs/heads/master/rpcs3/rpcs3.metainfo.xml -O ./content/apps/rpcs3/rpcs3.metainfo.xml &
wget -q https://raw.githubusercontent.com/martinrotter/rssguard/refs/heads/master/resources/desktop/rssguard.metainfo.xml.in -O ./content/apps/rssguard/io.github.martinrotter.rssguard.metainfo.xml &
wget -q https://raw.githubusercontent.com/rustdesk/rustdesk/refs/heads/master/flatpak/com.rustdesk.RustDesk.metainfo.xml -O ./content/apps/rustdesk/com.rustdesk.RustDesk.metainfo.xml &
wget -q https://raw.githubusercontent.com/scribusproject/scribus/refs/heads/master/scribus.appdata.xml.in -O ./content/apps/scribus/org.scribus.Scribus.metainfo.xml &
wget -q https://raw.githubusercontent.com/mltframework/shotcut/refs/heads/master/packaging/linux/org.shotcut.Shotcut.metainfo.xml.in -O ./content/apps/shotcut/org.shotcut.Shotcut.metainfo.xml &
wget -q https://raw.githubusercontent.com/simplex-chat/simplex-chat/refs/heads/stable/scripts/flatpak/chat.simplex.simplex.metainfo.xml -O ./content/apps/simplex/chat.simplex.simplex.metainfo.xml &
wget -q https://raw.githubusercontent.com/ransome1/sleek/refs/heads/main/flatpak/com.github.ransome1.sleek.appdata.xml -O ./content/apps/sleek/com.github.ransome1.sleek.metainfo.xml &
wget -q https://raw.githubusercontent.com/smplayer-dev/smplayer/refs/heads/master/smplayer.appdata.xml  -O ./content/apps/smplayer/info.smplayer.SMPlayer.metainfo.xml &
wget -q https://raw.githubusercontent.com/sqlitebrowser/sqlitebrowser/refs/heads/master/distri/sqlitebrowser.metainfo.xml -O ./content/apps/sqlitebrowser/org.sqlitebrowser.SqliteBrowser.metainfo.xml &
wget -q https://raw.githubusercontent.com/story-apps/starc/refs/heads/master/build/linux/flathub/share/metainfo/dev.storyapps.starc.metainfo.xml -O ./content/apps/starc/dev.storyapps.starc.metainfo.xml &
wget -q https://raw.githubusercontent.com/Stellarium/stellarium/refs/heads/master/data/org.stellarium.Stellarium.appdata.xml -O ./content/apps/stellarium/org.stellarium.Stellarium.metainfo.xml &
wget -q https://raw.githubusercontent.com/LizardByte/Sunshine/refs/heads/master/packaging/linux/dev.lizardbyte.app.Sunshine.metainfo.xml -O ./content/apps/sunshine/dev.lizardbyte.app.Sunshine.metainfo.xml &
wget -q https://raw.githubusercontent.com/IsmaelMartinez/teams-for-linux/refs/heads/main/com.github.IsmaelMartinez.teams_for_linux.appdata.xml -O ./content/apps/teams_for_linux/com.github.IsmaelMartinez.teams_for_linux.metainfo.xml &
wget -q https://codeberg.org/tenacityteam/tenacity/raw/branch/main/help/org.tenacityaudio.Tenacity.metainfo.xml -O ./content/apps/tenacity/org.tenacityaudio.Tenacity.metainfo.xml &
wget -q https://raw.githubusercontent.com/mapeditor/tiled/refs/heads/master/org.mapeditor.Tiled.appdata.xml -O ./content/apps/tiled/org.mapeditor.Tiled.metainfo.xml &
wget -q https://raw.githubusercontent.com/upscayl/upscayl/refs/heads/main/flatpak/org.upscayl.Upscayl.metainfo.xml -O ./content/apps/upscayl/org.upscayl.Upscayl.metainfo.xml &
wget -q https://github.com/Vencord/Vesktop/releases/latest/download/dev.vencord.Vesktop.metainfo.xml -O ./content/apps/vesktop/dev.vencord.Vesktop.metainfo.xml &
wget -q https://raw.githubusercontent.com/vifm/vifm/refs/heads/master/data/vifm.appdata.xml -O ./content/apps/vifm/info.vifm.vifm.metainfo.xml &
wget -q https://raw.githubusercontent.com/wezterm/wezterm/refs/heads/main/assets/wezterm.appdata.xml -O ./content/apps/wezterm/org.wezfurlong.wezterm.metainfo.xml &
wget -q https://raw.githubusercontent.com/xonsh/xonsh/refs/heads/main/appimage/xonsh.appdata.xml -O ./content/apps/xonsh/xonsh.metainfo.xml &
wget -q https://raw.githubusercontent.com/xournalpp/xournalpp/refs/heads/master/resources-templates/com.github.xournalpp.xournalpp.appdata.xml.in -O ./content/apps/xournalpp/org.xournalpp.xournalpp.metainfo.xml
