name: Update AppImage Download Links

on:
  schedule:
    # Запуск каждое воскресенье в 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:
    # Позволяет запускать скрипт вручную из вкладки Actions

permissions:
  contents: write # Дает право GitHub Actions коммитить изменения обратно в репозиторий
  id-token: write

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Скачивает всю историю, чтобы избежать проблем с правами на push
          fetch-depth: 0

      - name: Run AppImage updater script
        env:
          # Передаем системный токен GitHub, который уберет ограничение API Rate Limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./code/shittyscraper.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update download links - $(date)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}